# Jekyll configuration for GitHub Pages
title: My Portfolio
description: Jampani Komal's Portfolio Website
baseurl: ""
url: "https://jampanikomal.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include files
include:
  - assets
  - pages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap